import { IProduct } from "../../types/index";

export const productsData: Array<IProduct> = [
  {
    id: "0",
    title: "Erkek Gri Örme Yarım Fermuar Oversize Sweatshirt",
    imageUrl:
      "https://www.slatra.com.tr/Uploads/UrunResimleri/thumb/erkek-acikgri-orme-yarim-fermuar-overs-bbc417.jpg",
    price: "250,55",
    avaibleSizes: ["xl"],
    avaibleColors: ["black", "red"],
    categoryName: "üst giyim",
    clotheModel: "gömlek",
    discountPrice: "195.5",
    isFavorite: true,
    currency: "TL",
    deliverTime: "2 Gün",
    productDescription: "",
    productProperties: [{ name: "kumaş", value: "%100 Pamuk / %100 Cotton" }],
    stock: 0,
  },
  {
    id: "1",
    title: "Unisex Mavi W ÇıtÇıtlı Oversize Peluş Ceket",
    imageUrl:
      "https://www.slatra.com.tr/Uploads/UrunResimleri/thumb/unisex-mavi-w-citcitli-oversize-pelus--78-f04.jpg",
    price: "250,55",
    avaibleSizes: ["s", "m", "xl"],
    avaibleColors: ["black"],
    categoryName: "üst giyim",
    clotheModel: "sweatshirt",
    discountPrice: "0",
    isFavorite: false,
    currency: "TL",
    deliverTime: "2 Gün",
    productDescription: "",
    productProperties: [{ name: "kumaş", value: "%100 Pamuk / %100 Cotton" }],
    stock: 3,
  },
  {
    id: "2",
    title: "Unisex Siyah W ÇıtÇıtlı Oversize Peluş Ceket",
    imageUrl:
      "https://www.slatra.com.tr/Uploads/UrunResimleri/thumb/unisex-siyah-w-citcitli-oversize-pelus-dcf114.jpg",
    price: "250,55",
    avaibleSizes: ["s", "m", "xl"],
    avaibleColors: ["black"],
    categoryName: "üst giyim",
    clotheModel: "sweatshirt",
    discountPrice: "0",
    isFavorite: false,
    currency: "TL",
    deliverTime: "2 Gün",
    productDescription: "",
    productProperties: [{ name: "kumaş", value: "%100 Pamuk / %100 Cotton" }],
    stock: 10,
  },
  {
    id: "3",
    title: "Erkek Gri Örme Yarım Fermuar Oversize Sweatshirt",
    imageUrl:
      "https://st2.myideasoft.com/idea/jq/35/myassets/products/076/8508228a-08b0-4f95-a124-05ed5e80e721.jpg?revision=1645306292",
    price: "250,55",
    avaibleSizes: ["s", "m", "xl"],
    avaibleColors: ["black"],
    categoryName: "üst giyim",
    clotheModel: "sweatshirt",
    discountPrice: "0",
    isFavorite: false,
    currency: "TL",
    deliverTime: "2 Gün",
    productDescription: "",
    productProperties: [{ name: "kumaş", value: "%100 Pamuk / %100 Cotton" }],
    stock: 20,
  },
];
